<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>TARGET_FRAMEWORK_PLACEHOLDER</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pt.Okx.Sdk" Version="0.12.0-beta.2" />
  </ItemGroup>

</Project>
