<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>TARGET_FRAMEWORK_PLACEHOLDER</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <!--#if (useProjectReference) -->
    <ProjectReference Include="..\..\Pt.Okx.Sdk\Pt.Okx.Sdk.csproj" />
    <!--#else -->
    <PackageReference Include="Pt.Okx.Sdk" Version="0.12.0-beta.2" />
    <!--#endif -->
  </ItemGroup>

</Project>
